spring.application.name=admin

spring.datasource.url=jdbc:postgresql://localhost:5432/admin
spring.datasource.username=user
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=none

spring.jpa.properties.hibernate.dialect=ru.zharov.admin.fts.CustomPostgreSQLDialect

spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.format_sql=true